/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema representing challenges index.
 */
export interface ChallengeIndex {
  /**
   * Unique identifier for the index.
   */
  id: string;
  /**
   * Index type
   */
  type: "story" | "skillTree";
  /**
   * If it is a skillTree index, this identifier points to the particular tree.
   */
  skillTreeId?: string;
  challenges: string[];
}
