/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for defining test cases for code submission and expected results.
 */
export interface CodeWritingExpectations {
  /**
   * Associated challenge
   */
  challengeId: string;
  type: "codeWriting";
  /**
   * List of functions and their test configurations.
   */
  functions: TestSuite[];
}
export interface TestSuite {
  /**
   * Name of the function to be tested.
   */
  functionName: string;
  /**
   * A brief description of what the function does.
   */
  description?: string;
  /**
   * A list of test cases for this function.
   */
  testCases: TestCase[];
}
export interface TestCase {
  /**
   * An array representing the input parameters for the function.
   */
  input: unknown[];
  /**
   * The expected result of the test. Can be any type.
   */
  expectedOutput:
    | string
    | number
    | boolean
    | unknown[]
    | null
    | {
        [k: string]: unknown;
      };
  /**
   * A matcher function to use for verifying results.
   */
  matcherType: "strictEqual" | "deepEqual";
  /**
   * A brief description of what the test case is validating.
   */
  description?: string;
}
