/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A challenge that has at least one function for further implementation by users.
 */
export interface CodeWritingChallenge {
  /**
   * Unique identifier for the challenge.
   */
  id: string;
  type: "codeWriting";
  /**
   * Title of the challenge.
   */
  title: string;
  content: {
    /**
     * Markdown-supported text describing the challenge.
     */
    description: string;
    /**
     * List of hints in Markdown format.
     */
    hints: string[];
  };
  /**
   * Starter code provided for the challenge.
   */
  boilerplateCode: string;
  /**
   * The challenge cannot be completed unless dependent challenges are completed
   */
  dependencies: string[];
}
