/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A challenge that has at leasst one function for further implementation by users.
 */
export interface DnDChallenge {
  /**
   * Unique identifier for the challenge.
   */
  id: string;
  type: "dnd";
  /**
   * Title of the challenge.
   */
  title: string;
  content: {
    /**
     * Markdown-supported text describing the challenge.
     */
    description: string;
    /**
     * List of hints in Markdown format.
     */
    hints: string[];
  };
  /**
   * Starter data provided for the challenge
   */
  data: DnDList[];
  /**
   * The challenge cannot be completed unless dependent challenges are completed
   */
  dependencies: string[];
}
/**
 * An array of objects that needs to be rearranged between lists
 */
export interface DnDList {
  title: string;
  data: DnDListItem[];
}
/**
 * Objects that needs to be rearranged between lists
 */
export interface DnDListItem {
  title: string;
  description: string;
}
