/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema representing a skill tree structure.
 */
export interface SkillTree {
  /**
   * Unique identifier for the skill tree.
   */
  id: string;
  /**
   * Name of the skill tree.
   */
  name: string;
  /**
   * Detailed description of the skill tree.
   */
  description: string;
}
